version: '3.8'

services:
  apache:
    image: httpd
    restart: always
    ports:
      - 80:80
    volumes:
      - ./site:/usr/local/apache2/htdocs
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
